version: '3.7'

services:
  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3001:3000"  # Grafana dashboard on localhost:3001
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  # networks:
  #     - gofiber-observability
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"   # Web UI: http://localhost:16686
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"     # Zipkin-compatible
      - "4318:4318"
      - "4317:4317"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    # networks:
    #   - gofiber-observability

# volumes:
#   grafana-storage:
    
# networks:
#   gofiber-observability:
#     external: true
